### ISSUE TITLE
Return type of `usePendingFormSubmit()` should be possibly undefined or null

### ISSUE THREAD

**Issue by itsMapleLeaf** [smeijer/next-runtime#14]
The signature right now:
```ts
function usePendingFormSubmit(): {
    state: "pending";
    data: FormData;
}
```
Needs to be nullable to enforce existence checks

**Comment by smeijer** [comment]
We've released https://github.com/smeijer/next-runtime/releases/tag/v2.0.0. [`useFormSubmit`](https://next-runtime.meijer.ws/api/use-form-submit) now returns an `{ status: 'idle' }` as initial state.
