### ISSUE TITLE
Form pending state should wait for navigation

### ISSUE THREAD

**Issue by itsMapleLeaf** [smeijer/next-runtime#15]
This is a very unscientific demo, but it should help illustrate the point regardless:

https://user-images.githubusercontent.com/19603573/133911314-3d78ed70-5100-4c5f-b936-f196ed037420.mp4

This is my work in progress trello-like app. It uses the pending form submission to show placeholders while the actual update is happening in the backend.

At the moment, the form is considered submitted after the form request is completed. You can see this in the video: the pending states stop before the data is actually updated, and I've also included the devtool network requests for clarity. 

I think it would be more helpful to wait until the form request _and_ the navigation is complete for the form to be considered done

**Comment by smeijer** [comment]
We've released https://github.com/smeijer/next-runtime/releases/tag/v2.0.0. [`useFormSubmit`](https://next-runtime.meijer.ws/api/use-form-submit) returns a `status` as well as boolean helpers like `isLoading`.

- `status` 

  transitions from `idle` to `submitting` to `routing`, and ends in either `success` or `error`. In case there is no redirect returned, `routing` is skipped.

- `isLoading` 

  is true if `status` is either `submitting` or `routing`.
