### ISSUE TITLE
Pending form data should be deserialized as it is on the server

### ISSUE THREAD

**Issue by itsMapleLeaf** [smeijer/next-runtime#17]
Right now, I have to do this:
```ts
  const pending = usePendingFormSubmit()
  const newColumnName = pending?.data.get("createColumn.name")
  const deletedColumnId = pending?.data.get("deleteColumn.id")
```
Which makes sense, as those are the actual names of the <input> fields that I'm using, but it'd be convenient to have the body on the client in the same object shape as the body on the server, with the nested fields. So, I could do `pending?.body.createColumn?.name`, and reuse the same body type on the client. We should also keep the actual form data around too, just in case it's needed for whatever reason ¯\\\_(ツ)\_/¯

**Comment by smeijer** [comment]
How about exposing the `expand` utility?

`formDataToObject(pending?.data).createColumn?.name

I think having both a `data` and a `body` prop can be a bit confusing? Or not?
