### ISSUE TITLE
Add support for express middleware? 

### ISSUE THREAD

**Issue by smeijer** [smeijer/next-runtime#21]
Just a random thought, but next has currently not really a convinient way to support middleware. We could change that, and support middleware as option to `handle`.

A rough sketch:

```js
handle({
  use: [currentUser, cors],
  get() { ... },
})
```

The signature would be compatible with Express, so that most existing middlewares could be used.

Middlewares should be able to return and throw responses.

- Thrown responses are final.

- Returned responses are merged with other return values if they hold props, or final if it's a not Found or redirect.

**Comment by MichaelDeBoey** [comment]
Next.js reference: https://nextjs.org/docs/api-routes/api-middlewares#connectexpress-middleware-support

**Comment by smeijer** [comment]
As I mentioned, not really convenient 😅.
