### ISSUE TITLE
"cannot read property 'headers' of undefined" error after upgrading to 2.0.0

### ISSUE THREAD

**Issue by tconroy** [smeijer/next-runtime#28]
Upgraded to 2.0.0 this morning and started getting the below:
```
error - TypeError: Cannot read property 'headers' of undefined
    at new Accepts (/node_modules/accepts/index.js:37:22)
    at Accepts (/node_modules/accepts/index.js:34:12)
    at applyResponse (/node_modules/next-runtime/handle.js:40:35)
    at /node_modules/next-runtime/handle.js:111:36
    at Generator.next (<anonymous>)
    at fulfilled (/node_modules/next-runtime/handle.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  page: '/dashboard'
```

Here is the handle implementation on my `/dashboard` page:

```
export const getServerSideProps = handle({
  get: async (context) => {
   // supabase query. truncated for brevity.
    const { error, data: organizations } = await supabaseClient....

    return json({ error, organizations, user: context.req.user });
  }
});
```

the above works as expected with the latest 1.x code when performing an HTML request, but errors on 2.0.0.

The error seems to terminate at the `req.headers` access in `Accepts/index.js`:
```
function Accepts (req) {
  if (!(this instanceof Accepts)) {
    return new Accepts(req)
  }

  this.headers = req.headers <<<<<<<< here
  this.negotiator = new Negotiator(req)
}
```

**Comment by smeijer** [comment]
Thanks for the report! What version of node & next.js do you use?

**Comment by smeijer** [comment]
I've pushed an update that might fix this, but without knowing which node & next versions were used, I can't be sure. Please let me know if it works :)

https://github.com/smeijer/next-runtime/releases/tag/v2.0.1

**Comment by tconroy** [comment]
Hey there, thanks for the reply!

I'm using node v15.5.0 & next v11.1.2. 

I'll give the new version a try right now, thanks!
