### ISSUE TITLE
Add back `onSuccess` and `onError` handlers to `Form`

### ISSUE THREAD

**Issue by itsMapleLeaf** [smeijer/next-runtime#31]
I actually didn't realize these were gone until I tried to use them 😆 

So, from reading the docs, I figure the rationale was that the onSuccess/onError callbacks were used to update state to show some message in the UI. The `useFormSubmit` state works fine in that case. But when I need to fire some side effect, the hook state feels more cumbersome.

Here's an example and comparison. The modal accepts a render prop for a `close` function.

Without the `onSuccess` callback, I need to use a `useEffect` that relies on the hook state, which also requires making a new component in which to use the hook:
```js
export function EditBucketButton({ bucket }) {
  return (
    <Modal
      title="edit bucket"
      renderContent={({ close }) => (
        <EditBucketForm bucket={bucket} onSuccess={close} />
      )}
    />
  )
}

function EditBucketForm({ bucket, onSuccess }) {
  const { isSuccess } = useFormSubmit("edit-bucket")

  useEffect(() => {
    if (isSuccess) onSuccess()
  }, [isSuccess, onSuccess])

  return (
    <Form name="edit-bucket" action={`/buckets/${bucket.id}`} method="patch">
      {/* form stuff */}
    </Form>
  )
}
```

With the callback, I don't need a new component. I can write the form inline, and pass the close callback to `onSuccess`:
```js
export function EditBucketButton({ bucket }) {
  return (
    <Modal
      title="edit bucket"
      renderContent={({ close }) => (
        <Form name="edit-bucket" action={`/buckets/${bucket.id}`} method="patch" onSuccess={close}>
          {/* form stuff */}
        </Form>
      )}
    />
  )
}
```
Summary: the callbacks seem valuable as a convenient way to run side effects in response to a form submission.

In this specific case, I could refactor `Modal` to just accept props, then I could have all of the state + the effect in one component, but writing an effect for each instance of this still doesn't sound like fun 😅 That, and [there are other APIs that work like this](https://headlessui.dev/react/disclosure#closing-disclosures-manually), as a point of reference.

**Comment by smeijer** [comment]
Fine by me. We can simply put the effects in Form instead, and pass the full state as param to the callback.

**Comment by itsMapleLeaf** [comment]
I have some free time, so I'll add this one in 🙂
