### ISSUE TITLE
example not working?

### ISSUE THREAD

**Issue by evertbouw** [smeijer/next-runtime#33]
I got a bit confused from the docs. The main example doesn't show the message after making the post. You can fix this by using lower case `form`, reading the data from the hook, or adding `withNextRuntime`. The note on the last docs page suggests the second option. Should the other pages reflect this?

**Comment by smeijer** [comment]
I think we should revert #1 . Being able to show that we can work with `form` is a strong selling point. It was as intended, and I shouldn't have merged it.
