### ISSUE TITLE
`json()` should also accept a `status` option

### ISSUE THREAD

**Issue by itsMapleLeaf** [smeijer/next-runtime#4]
A 200 status for all responses _works_, but being able to give a 4xx for bad responses would definitely feel more proper

**Comment by smeijer** [comment]
Sounds like a nice addition.

**Comment by Siemko** [comment]
@smeijer I've seen that you've already implemented Responses from `node-fetch` with `ReponseInit`, so I believe this one is resolved, correct?

**Comment by smeijer** [comment]
Published as https://github.com/smeijer/next-runtime/releases/tag/v1.2.0. I'll work on the docs later, but here's an example:

https://github.com/smeijer/next-runtime/blob/7ccae3e48b8ea1ec394bb8e957160057426a85f9/src/responses.test.ts#L78-L82
