### ISSUE TITLE
Form component does not work after updating to Next12

### ISSUE THREAD

**Issue by AndersGerner** [smeijer/next-runtime#43]
Thanks for a great library! Really love this!

After updating to Next12, using the Form component, which sets the header: "Accept": "application/json", this request are just pending. using the normal HTML "form" element still works. 
If you make a post request, without the "accept" header, the text/html is returned with the expected data from the handler in the next/script at the bottom.

I have created this repository to help reproduce the error: https://github.com/AndersGerner/Next12RuntimeFormError

I have tried to google and look around but I am unfortunately not able to help - Hoping you guys have an idea on this issue :) 

UPDATE:
Maybe not the Form that is the problem. Using the example CURL request: `curl -H "Accept: application/json" https://example.com/page-path` is also pending. So maybe it's the handler?

**Comment by apiep** [comment]
I might need to make a separated issue for this. Also on nextjs 12.

I found that if my handler having a redirect as response,
if using dev server `next dev` it will hang the request (browser still showing loading state), but it redirect successfully if using prod server `next build && next start`

**Comment by AndersGerner** [comment]
@apiep AWESOME INPUT!
I see, that my issue is also solved with prod build. 

This is only an issue when using `next dev`

**Comment by smeijer** [comment]
Thanks for creating this ticket! 

I have a very basic reproduction that doesn't involve `next-runtime`, but does something similar to what next-runtime does under the hood. Basically, we just intercept the `response` object, and end it early. 

```jsx
export function getServerSideProps({ req, res }) {
  if (req.headers["accept"].startsWith("application/json")) {
    res.end(JSON.stringify({ time: new Date() }));
    return { props: { } };
  }

  return { props: { } };
}

export default function IndexPage() {
  return null;
}
```

That's it. That works in Next 11, but not in 12. I've extended that case with a "fetch button" and made two code sandboxes to confirm this. 

[next 11](https://codesandbox.io/s/next-11-gssp-uj9dw?file=/pages/index.js)
- click `fetch`
- see `pending` and `{ time: "..." }` as result
 
[next 12](https://codesandbox.io/s/next-12-gssp-pyy0q?file=/pages/index.js). 
- click `fetch`
- see `pending`... and stuck.

**Comment by smeijer** [comment]
I'll try to find a fix, but as it seems that they no longer allow us to handle the HTTP response ourselves, I don't have high hopes. Any help would be appreciated.

**Comment by apiep** [comment]
I was able to fix the hang request by removing `res.end()` in handle.ts, but not sure what will the side effect by removing that code :)

**Comment by smeijer** [comment]
That works for the `redirect`, but not for requesting `json`, which is used by `Form`.

**Comment by apiep** [comment]
What about using `redirect.statusCode` property when returning object from getServerSideProps? Like shown in this documentation https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering

**Comment by smeijer** [comment]
Sweet! using `statusCode` instead of `permanent` works for the status code.  

Remaining, json support.

**Comment by smeijer** [comment]
This commit should fix the redirect: [`48d4f50`](https://github.com/smeijer/next-runtime/pull/44/commits/48d4f50c8c3cedb34d4f1c5647efdf4fff4ec6a1) (unpublished)

**Comment by AndersGerner** [comment]
It seems, that if I instead of `return json({})` use the following, it works in Next12
```
res.setHeader('Content-Type', 'application/json')
res.write(JSON.stringify({}))
res.end()
```

I will continue investigating.

Awesome that the redirect is fixed!!

**Comment by AndersGerner** [comment]
It acutally also kinda works, with just setting the header:

```
res.setHeader('Content-Type', 'application/json')
return json({))
```
It gives this error in the log though:

> error - Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

**Comment by smeijer** [comment]
Are you sure? Because it doesn't on codesandbox.

```tsx
import { useRef } from "react";

export function getServerSideProps({ req, res }) {
  if (req.headers["accept"].startsWith("application/json")) {
    res.setHeader("Content-Type", "application/json");
    res.write(JSON.stringify({}));
    // res.end();
    // return;
  }

  return {
    props: { hi: "there" }
  };
}

export default function IndexPage() {
  const ref = useRef();

  const goFetch = () => {
    ref.current.innerHTML = "fetching...";
    fetch("/", {
      headers: {
        accept: "application/json"
      }
    })
      .then((res) => res.json())
      .then((data) => (ref.current.innerHTML = JSON.stringify(data, null, 2)));
  };

  return (
    <div>
      <button onClick={goFetch}>fetch</button>
      <pre ref={ref} />
    </div>
  );
}
```

https://codesandbox.io/s/next-12-gssp-forked-9gsyl?file=/pages/index.js:0-765

**Comment by AndersGerner** [comment]
@smeijer This is wierd. 
When running it in CodeSandbox: https://codesandbox.io/s/small-violet-nbghj I can't get it to work, but when I run it locally based on the repo: https://github.com/AndersGerner/Next12RuntimeFormError.git it works. 

For the following code:

```
import { handle, json } from "next-runtime";
import { Form, useFormSubmit } from 'next-runtime/form'

export const getServerSideProps = handle({
  async get() {
    return json({ name: "initial name" });
  },

  async post({ req, res }) {
    console.log('req.headers["accept"]',req.headers["accept"])
    if (req.headers["accept"].startsWith("application/json")) {
      res.setHeader("Content-Type", "application/json");
      res.write(JSON.stringify({ message: `Submitted ${req.body.name}` }));
      res.end()
    }
  }
});

export default function HtmlForm(props) {

  const form = useFormSubmit('nameForm');

  if (form.isLoading) {
    return <p>{`Currently submitting ${form.values.name}`}</p>;
  }

  if (form?.data?.message) {
    return <p>{`${form.data.message}`}</p>;
  }

  return (
  <>
    {form?.data?.message && <p>{form.data.message}</p>}
    <Form method="post" name="nameForm">
      <input name="name" defaultValue={props.name} />
      <input type="submit" />
      </Form>
      </>
  );
}

```

Do you think, it could be an idea to create an issue on their Github repo to ask, about changes from 11->12 in regards to the responses and the ability to adjust it. ? I can create it, but I might need some extra input from you, to be precisely on point where the issues are.

**Comment by smeijer** [comment]
Yeah, creating an issue might be worth it. I mean, the basic code sandbox examples that I shared earlier should (ideally) just behave the same.

In the meanwhile, I've published https://github.com/smeijer/next-runtime/releases/tag/v2.3.1 to support `redirect` in Next 12.

**Comment by smeijer** [comment]
Ok, weird. When I run that repo, I do see an HTTP error on the console that we can't ignore. But I am able to adjust it to a standard handler without `next-runtime` that doesn't keep pending, and still returns json. I'll try to dive into it somewhere this week.

For reference, the following does work:

```
export const getServerSideProps = ({ req, res }) => {
  console.log(req.headers.accept);

  if (req.method === "POST") {
    console.log('handle post');
    res.setHeader("Content-Type", "application/json");
    res.write(JSON.stringify({ message: `Submitted` }));
    res.end()

    return { props: {} };
  }

  if (req.headers.accept.startsWith('application/json')) {
    res.setHeader("Content-Type", "application/json");
    res.write(JSON.stringify({ message: `huh` }));
    res.end()

    return { props: {} };
  }

  return { props: { method: "get" } }
}
```

**Comment by smeijer** [comment]
I THINK I HAVE IT!

**this doesn't work**
```js
    res.end(JSON.stringify({ message: "submitted" })); 
    return { props: { } };
```

**this works**
```js
    res.write(JSON.stringify({ message: `Submitted` }));
    res.end(); 
    return { props: { } };
```

So, it doesn't make much sense, but it seems to do the trick.

**Comment by smeijer** [comment]
Fixed! Please try https://github.com/smeijer/next-runtime/releases/tag/v2.3.2 and let me know if it works.

**Comment by AndersGerner** [comment]
@smeijer  YEEES!!!! YOU ARE THE MAN!

2.3.2 works! Thank you!
I have tested both in my project and in the test-repo and it just works perfectly now!
