### ISSUE TITLE
Type error in ref props of the Form component

### ISSUE THREAD

**Issue by KoichiKiyokawa** [smeijer/next-runtime#46]
First, thank you for such a nice library :tada:

There is a type error when I pass `ref` to the `<Form>` component (but, it works well, just a type error).

![image](https://user-images.githubusercontent.com/40315079/148877382-7f6c02cb-9624-4446-ac22-1bb5a49fdf29.png)

repro: https://stackblitz.com/edit/nextjs-9mtrvu?file=pages/index.tsx

**Comment by smeijer** [comment]
Thanks for the report. I don't have time to look into it today, but I'll come back to you! If you by any chance have the time and mood to work on a fix, then please do. It would be much appreciated.

I suspect this cast from being the trouble maker:

https://github.com/smeijer/next-runtime/blob/8a2da59e9d343f032e76cca5f191f21fe136fe0c/src/form/form.tsx#L83-L84
