### ISSUE TITLE
Support redirecting to another page with POST

### ISSUE THREAD

**Issue by itsMapleLeaf** [smeijer/next-runtime#5]
I might be misunderstanding or doing something wrong here 😅 but either way, here's my scenario:

- User logs in from the login page
- On success, they get redirected to another page
- That other page has a `POST` handler, which accepts data

Because the request to /login was a POST, the redirect is _also_ a POST, and that POST redirect is sending the login data, which the other page's POST doesn't expect.

And there's nothing fancy going on in the login page, it's just a regular redirect:
```js
export const getServerSideProps = handle<Props>({
  async post(context) {
    // check credentials + create session

    return redirect("/")
  },
})
```

I _think_ what's needed here is being able to define the redirect method, e.g. `redirect('/', { method: 'GET' })`. Or maybe the redirect should _always_ be a no-data GET? Or maybe the real solution is to move the other page's POST handler into a dedicated API route... 🤔 thoughts appreciated, I can also clarify anything here if need be

Ah, I should also mention that this is with JS disabled

**Comment by smeijer** [comment]
It's not you. It needs some refactoring to support this scenario. I've got some ideas, and will get on it.

What it must do, is turn the POST into a GET request, and drop the data.

**Comment by smeijer** [comment]
Should be fixed on `main`.

**Comment by smeijer** [comment]
Released as https://github.com/smeijer/next-runtime/releases/tag/v1.2.0. Please let me know if it works.
