### ISSUE TITLE
dependency vunlunbility 

### ISSUE THREAD

**Issue by ripple0328** [smeijer/next-runtime#66]
dependency **busboy**  <=0.3.1 depend on **dicer** 
which has vunlunbility, is it possible to upgrade, I saw 1.6 available

```
dicer  *
Severity: high
Crash in HeaderParser in dicer - https://github.com/advisories/GHSA-wm7h-9275-46v2

```

**Comment by smeijer** [comment]
Happy to merge a pull that fixes it.

**Comment by PandiyanCool** [comment]
Hi @smeijer 

I have raised PR 

https://github.com/smeijer/next-runtime/pull/76

Please take a look, and see whether that works.

**Comment by PandiyanCool** [comment]
@smeijer - this issue can be closed now because of this fix https://github.com/smeijer/next-runtime/pull/76

**Comment by smeijer** [comment]
Thanks!

**Comment by PandiyanCool** [comment]
How can I trigger all-contributions bot? for code contribution. @smeijer

**Comment by smeijer** [comment]
Done! Sorry for missing that, and thanks again. 🙂

**Comment by PandiyanCool** [comment]
No problem 👍🏻
